[workspace]
members = ["crds", "operator", "manifest-gen"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
k8s-openapi = { version = "0.25.0", features = ["v1_33"] }
kube = "1.1.0"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.141"
