version = 1

[[annotations]]
path = [
  "README.md",
  "Cargo.lock",
  "go.sum",
  "PROJECT",
  "operator/src/kbs-config.toml",
  "operator/src/resource.rego",
  "operator/src/tpm.rego",
  "docs/pics/*",
  "docs/design/*"
]
SPDX-FileCopyrightText = [
    "Alice Frosi <afrosi@redhat.com>",
    "Jakob Naucke <jnaucke@redhat.com>"
]
SPDX-License-Identifier = "CC0-1.0"
