# SPDX-FileCopyrightText: Jakob Naucke <jnaucke@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

# This rule is not used by the project trusted-cluster-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over confidential-clusters.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trusted-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: machine-admin-role
rules:
- apiGroups:
  - confidential-clusters.io
  resources:
  - machines
  verbs:
  - '*'
- apiGroups:
  - confidential-clusters.io
  resources:
  - machines/status
  verbs:
  - get
