[package]
name = "crds"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
k8s-openapi.workspace = true
kube.workspace = true
schemars = { version = "0.8", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
